### ISSUE TITLE
Create mock ups of website

### ISSUE THREAD

**Issue by pmallari** [pmallari/emotion_tracker#5]

**Comment by AlexFloresVeliz** [comment]
Current mock up of the site can be found here: https://xd.adobe.com/view/0e1020b4-7576-447b-4635-fcafadf5af1a-7821/

Comments are allowed! @pmallari

**Comment by AlexFloresVeliz** [comment]
Final Mockup can be found at this link and accessed at any time:

https://xd.adobe.com/view/0e1020b4-7576-447b-4635-fcafadf5af1a-7821/

@pmallari
